name = "lyrical-vector-ingest"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "LYRICAL_DB"
database_name = "lyrical-miracles"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "lyrical-miracles"
remote = true

[env.production]
workers_dev = true

[[env.production.d1_databases]]
binding = "LYRICAL_DB"
database_name = "lyrical-miracles"

[[env.production.vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "lyrical-miracles"
remote = true
